stages:
  - test-job
  - check-database
  - production

test-job:
  stage: test-job
  tags:
    - Builder 
  script:
    - echo "Running tests on Test branch1"
    - echo "Checking mysql connection"
    - export MYSQL_HOST=$MYSQL_HOST
    - export MYSQL_PORT=$MYSQL_PORT
    - export MYSQL_ROOT_USER=$MYSQL_ROOT_USER
    - export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    - export DATABASES=$MYSQL_DB_NAME,$TEST_DB_NAME
    - python3 -m venv venv 
    - source venv/bin/activate
    - pip install mysql-connector-python
    - result=$(python3 database/check-mysql.py)
    - |
      if [ "$result" == "true" ]; then
        echo "===Database is Running==="
      else
        echo "===Database is not Running==="
        exit 1
      fi

    - echo "===Getting Started with Python-Django Testing==="
    - docker build --build-arg HOST=$HOST --build-arg PORT=$PORT --build-arg MYSQL_ROOT_USER=$MYSQL_ROOT_USER --build-arg MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD --build-arg MYSQL_DB_NAME=$TEST_DB_NAME --build-arg SECRET_KEY=$SECRET_KEY -t $Dockerhub/python-django:latest .
    - echo "build completed"
    - echo "starting docker container for testing"
    - docker run -d --rm -p 8000:8000 --name python-django $Dockerhub/python-django:latest
    - echo "docker container is running. starting health tests"
    - pip install requests
    - python3 test/test.py
    - echo "=======Health checks passed========"

    - echo "pushing to python-django pre-production"
    - docker login -u "$Dockerhub" -p "$DOCKER_PASSWORD"
    - docker push $Dockerhub/python-django:latest
    - scp -r ./docker-compose.yml ubuntu@$PYTHON_PRE_PRODUCTION:/home/ubuntu/
    - ssh -T ubuntu@$PYTHON_PRE_PRODUCTION "echo 'connecting to pre-prod' && \
        echo 'Rebuilding docker-compose.' && \
        docker-compose down && \
        docker-compose pull && \
        docker-compose up -d && \
        docker ps"
    - echo "=====Completed====="
  rules:
    - if: '$CI_COMMIT_BRANCH == "Test"'


check-database:
  stage: check-database
  tags:
    - Builder 
  script:
      - echo "===Checking database connection==="
      - export MYSQL_HOST=$MYSQL_HOST
      - export MYSQL_PORT=$MYSQL_PORT
      - export MYSQL_ROOT_USER=$MYSQL_ROOT_USER
      - export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - export DATABASES=$MYSQL_DB_NAME,$TEST_DB_NAME
      - python3 -m venv venv 
      - source venv/bin/activate
      - pip install mysql-connector-python
      - result=$(python3 database/check-mysql.py)
      - |
        if [ "$result" == "true" ]; then
          echo "Database is running"
        else
          echo "===Mysql is not running==="
          scp -r ./database ubuntu@$MYSQL_EC2_HOST:/home/ubuntu/
          cd database/
          docker build --build-arg MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -t $Dockerhub/mysql-database:latest .
          docker login -u "$Dockerhub" -p "$DOCKER_PASSWORD"
          docker push $Dockerhub/mysql-database:latest
          echo "starting mysql again"
          ssh -T ubuntu@$MYSQL_EC2_HOST "echo 'connecting to mysql ec2' && \
            echo 'rebuilding docker-compose.' && \
            cd database/ && \
            docker-compose down && \
            docker-compose pull && \
            docker-compose up -d"
        fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'



production:
  stage: production
  tags:
    - Builder
  needs:
    - job: check-database
      artifacts: false 
  script:
    - echo "===Production==="

    - echo "building docker image"
    - docker build \
        --build-arg MYSQL_HOST=$MYSQL_HOST \
        --build-arg MYSQL_PORT=$MYSQL_PORT \
        --build-arg MYSQL_ROOT_USER=$MYSQL_ROOT_USER \
        --build-arg MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD \
        --build-arg MYSQL_DB_NAME=$MYSQL_DB_NAME \
        --build-arg SECRET_KEY=$SECRET_KEY \
        -t  $Dockerhub/python-django:latest .

    - docker login -u "$Dockerhub" -p "$DOCKER_PASSWORD"
    - echo "pushing docker image to dockerhub"
    - docker push $Dockerhub/python-django:latest
    - echo "image pushed to dockerhub"
    - echo "copying compose file to production"
    - scp -r ./docker-compose.yml ubuntu@$PYTHON_PRODUCTION:/home/ubuntu/

    - ssh -T ubuntu@$PYTHON_PRODUCTION "echo 'connecting to production' && \
        echo 'Rebuilding docker-compose.' && \
        docker-compose down && \
        docker-compose pull && \
        docker-compose up -d && \
        docker ps"
    - curl -f http://localhost:80/health || exit 1
    - echo "==========COMPLETED=========="
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'