# Generated by Django 5.1.3 on 2024-12-02 02:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreaction',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('author', 'comment')},
        ),
    ]
