# Generated by Django 5.1.3 on 2024-12-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.BooleanField(choices=[(1, 'Like'), (0, 'Dislike')], null=True),
        ),
    ]
